services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=db_development
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    env_file:
      - ./.env
    environment:
      - STRIPE_API_KEY
      - STRIPE_DEVICE_NAME
    entrypoint: >
      stripe listen 
      --forward-to http://host.docker.internal:5256/webhook	 
      --api-key $STRIPE_API_KEY
    extra_hosts:
      - "host.docker.internal:192.168.100.80"
    tty: true
    stdin_open: true
volumes:
  postgres-data:
  redis_data:
