services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=db_development
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres-data:
  redis_data:
