services:
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=db_development
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    environment:
      - STRIPE_API_KEY=${Stripe__ApiKey}
      - STRIPE_DEVICE_NAME=docker-dev
    entrypoint: >
      stripe listen --forward-to host.docker.internal:5256/webhook
    tty: true
    stdin_open: true
    env_file:
      - ./src/Api/.env.local

volumes:
  postgres-data:
  redis_data:
